### ISSUE TITLE
Incorrect role path in tasks/fs.yml

### ISSUE THREAD

**Issue by litelitelite** [linux-system-roles/gfs2#12]
Hello.
Incorrect role path in https://github.com/linux-system-roles/gfs2/blob/main/tasks/fs.yml#L15
Heres correct name: linux-system-roles.storage

**Comment by richm** [comment]
> Hello. Incorrect role path in https://github.com/linux-system-roles/gfs2/blob/main/tasks/fs.yml#L15 Heres correct name: linux-system-roles.storage

`fedora.linux_system_roles.storage` is correct - https://linux-system-roles.github.io/documentation/role-requirements.html
